// <auto-generated />
using System;
using Biblioteca_de_Jogos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Biblioteca_de_Jogos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430182146_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca_de_Jogos.Models.CodigoRecuperacao", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("Expiracao")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("Usado")
                    .HasColumnType("boolean");

                b.HasKey("Id");

                b.ToTable("CodigosRecuperacao");
            });

            modelBuilder.Entity("Biblioteca_de_Jogos.Models.Console", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Grupo")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Consoles");
            });

            modelBuilder.Entity("Biblioteca_de_Jogos.Models.Jogo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Console")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Dono")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("EmprestadoPara")
                    .HasColumnType("text");

                b.Property<bool>("EstaEmprestado")
                    .HasColumnType("boolean");

                b.Property<string>("FotoUrl")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Genero")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<int>("HorasParaZerar")
                    .HasColumnType("integer");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.ToTable("Jogos");
            });

            modelBuilder.Entity("Biblioteca_de_Jogos.Models.SolicitacaoEmprestimo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DataSolicitacao")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DonoNome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("JogoId")
                    .HasColumnType("integer");

                b.Property<string>("SolicitanteNome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<bool>("Visualizada")
                    .HasColumnType("boolean");

                b.HasKey("Id");

                b.HasIndex("JogoId");

                b.ToTable("Solicitacoes");
            });

            modelBuilder.Entity("Biblioteca_de_Jogos.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<bool>("IsAdmin")
                    .HasColumnType("boolean");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("Biblioteca_de_Jogos.Models.SolicitacaoEmprestimo", b =>
            {
                b.HasOne("Biblioteca_de_Jogos.Models.Jogo", "Jogo")
                    .WithMany()
                    .HasForeignKey("JogoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Jogo");
            });
#pragma warning restore 612, 618
        }
    }
}